const translations = {
    fr: {
        splashBtn: "Entrer dans l'espace rediffusion",
        navHome: "Accueil",
        navTeam: "L'Équipe",
        navJoin: "Rejoindre l'équipe",
        navHelp: "Aide",
        navCalendar: "Calendrier",
        navInstagram: "Instagram",
        navLogin: "Connexion",
        ready: "PRÊT À L'ÉCOUTE",
        playing: "LECTURE EN COURS",
        pause: "PAUSE",
        choosePodcast: "🎧 Choisissez une rediffusion ci-dessous",
        noPodcast: "Aucun podcast dans ce dossier.",
        listenBtn: "Écouter la rediffusion",
        confirmDelete: "Voulez-vous vraiment supprimer définitivement cette rediffusion ?",
        sectionTitle: "Liste des Rediffusions",
        adminTitle: "🛠️ Panneau de Gestion (Propriétaire)",
        adminSubtitle: "Ajouter une nouvelle rediffusion (via lien Internet Archive) :",
        lblTitle: "Titre de l'émission :",
        lblInfo: "Date ou détails :",
        lblFile: "Lien direct du MP3 :",
        btnSubmit: "Ajouter le podcast",
        uploadStatus: "Enregistrement du lien sur le serveur en cours...",
        btnLogout: "Se déconnecter",
        settingsTitle: "Réglages Généraux",
        settingsLang: "Langue :",
        settingsMedia: "Thème Visuel :",
        settingsMediaSsn: "Mode Saison (par défaut)",
        settingsMediaDft: "Mode Sombre",
        settingsMediaEar: "Mode clair",
        settingsFont: "Taille de la police :",
        settingsFontSm: "Petite",
        settingsFontMd: "Normale",
        settingsFontLg: "Grande",
        settingsSave: "Enregistrer les réglages",
        footer: "© 2026 Radio 6 - Espace de rediffusion du Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "L'Équipe de Radio 6",
        eqSub: "Découvrez les coulisses de la Radio d'Art 6 du Lycée Arcisse de Caumont à Bayeux.",
        eqH3Hours: "🕒 Horaires d'Ouverture du Studio",
        eqPHours: "Le club et le studio de la radio vous accueillent chaque semaine aux horaires suivants :",
        eqBadge: "Jeudi de 12h40 à 13h25",
        eqPDesc: "Passez nous voir au studio pour découvrir le matériel, assister aux enregistrements ou proposer vos idées d'émissions !",
        eqJoinTitle: "🎙️ Rejoignez l'aventure pour 2026 / 2027 !",
        eqJoinP1: "Tu es passionné par le son, l'actualité, la musique, la technique ou l'animation ? Tu as envie de faire entendre ta voix au lycée ?",
        eqJoinP2: "Si tu veux faire partie de l'équipe officielle de la radio pour la rentrée prochaine (saison 2026/2027), n'hésite plus !",
        eqJoinP3: "👉 Viens nous rencontrer directement au studio le Jeudi midi pour voir comment ça se passe et réserver ta place.",
        aiMainTitle: "Besoin d'aide pour écouter ?",
        aiMainSub: "Voici les solutions simples si vous rencontrez une difficulté sur notre espace de rediffusion.",
        instaMainTitle: "Comptes Instagram du Lycée",
        instaBtn: "Voir le profil"
    },
    de: { // Allemand
        splashBtn: "Wiedergabebereich betreten",
        navHome: "Startseite",
        navTeam: "Das Team",
        navJoin: "Dem Team beitreten",
        navHelp: "Hilfe",
        navCalendar: "Kalender",
        navInstagram: "Instagram",
        navLogin: "Anmelden",
        ready: "BEREIT ZUM ANHÖREN",
        playing: "WIEDERGABE LÄUFT",
        pause: "PAUSE",
        choosePodcast: "🎧 Wählen Sie unten eine Wiederholung aus",
        noPodcast: "Kein Podcast in diesem Ordner.",
        listenBtn: "Wiederholung anhören",
        confirmDelete: "Möchten Sie diese Wiederholung wirklich dauerhaft löschen?",
        sectionTitle: "Liste der Wiederholungen",
        adminTitle: "🛠️ Verwaltungsbereich (Eigentümer)",
        adminSubtitle: "Neue Wiederholung hinzufügen (über Internet Archive Link):",
        lblTitle: "Titel der Sendung:",
        lblInfo: "Datum oder Details:",
        lblFile: "Direkter MP3-Link:",
        btnSubmit: "Podcast hinzufügen",
        uploadStatus: "Link wird auf dem Server gespeichert...",
        btnLogout: "Abmelden",
        settingsTitle: "Allgemeine Einstellungen",
        settingsLang: "Sprache:",
        settingsMedia: "Visuelles Thema:",
        settingsMediaSsn: "Saisonmodus (Standard)",
        settingsMediaDft: "Dunkelmodus",
        settingsMediaEar: "Hellmodus",
        settingsFont: "Schriftgröße:",
        settingsFontSm: "Klein",
        settingsFontMd: "Normal",
        settingsFontLg: "Groß",
        settingsSave: "Einstellungen speichern",
        footer: "© 2026 Radio 6 - Wiedergabebereich des Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Das Team von Radio 6",
        eqSub: "Entdecken Sie die Kulissen von Radio d'Art 6 des Lycée Arcisse de Caumont in Bayeux.",
        eqH3Hours: "🕒 Öffnungszeiten des Studios",
        eqPHours: "Der Club und das Radiostudio heißen Sie jede Woche zu folgenden Zeiten willkommen:",
        eqBadge: "Donnerstag von 12:40 bis 13:25 Uhr",
        eqPDesc: "Besuchen Sie uns im Studio, um die Ausrüstung kennenzulernen, bei Aufnahmen dabei zu sein oder Ihre Sendungsideen vorzuschlagen!",
        eqJoinTitle: "🎙️ Werden Sie Teil des Abenteuers für 2026 / 2027!",
        eqJoinP1: "Begeistern Sie sich für Ton, Nachrichten, Musik, Technik oder Moderation? Möchten Sie Ihre Stimme in der Schule hörbar machen?",
        eqJoinP2: "Wenn Sie für das kommende Schuljahr (Saison 2026/2027) zum offiziellen Radioteam gehören möchten, zögern Sie nicht!",
        eqJoinP3: "👉 Treffen Sie uns donnerstags zur Mittagszeit direkt im Studio!",
        aiMainTitle: "Brauchen Sie Hilfe beim Anhören?",
        aiMainSub: "Hier sind einfache Lösungen, wenn Sie Schwierigkeiten auf unserer Wiedergabeplattform haben.",
        instaMainTitle: "Instagram-Konten des Gymnasiums",
        instaBtn: "Profil ansehen"
    },
    en: { // Anglais
        splashBtn: "Enter the replay area",
        navHome: "Home",
        navTeam: "The Team",
        navJoin: "Join the team",
        navHelp: "Help",
        navCalendar: "Calendar",
        navInstagram: "Instagram",
        navLogin: "Login",
        ready: "READY TO LISTEN",
        playing: "PLAYING",
        pause: "PAUSED",
        choosePodcast: "🎧 Choose a replay below",
        noPodcast: "No podcasts in this folder.",
        listenBtn: "Listen to the replay",
        confirmDelete: "Are you sure you want to permanently delete this replay?",
        sectionTitle: "Replay List",
        adminTitle: "🛠️ Management Panel (Owner)",
        adminSubtitle: "Add a new replay (via Internet Archive link):",
        lblTitle: "Show title:",
        lblInfo: "Date or details:",
        lblFile: "Direct MP3 Link:",
        btnSubmit: "Add podcast",
        uploadStatus: "Saving link to server...",
        btnLogout: "Log out",
        settingsTitle: "General Settings",
        settingsLang: "Language:",
        settingsMedia: "Visual Theme:",
        settingsMediaSsn: "Season Mode (default)",
        settingsMediaDft: "Dark Mode",
        settingsMediaEar: "Light mode",
        settingsFont: "Font size:",
        settingsFontSm: "Small",
        settingsFontMd: "Normal",
        settingsFontLg: "Large",
        settingsSave: "Save settings",
        footer: "© 2026 Radio 6 - Replay area of Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "The Radio 6 Team",
        eqSub: "Discover what goes on behind the scenes of Radio d'Art 6 at Lycée Arcisse de Caumont in Bayeux.",
        eqH3Hours: "🕒 Studio Opening Hours",
        eqPHours: "The radio club and studio welcome you every week during the following hours:",
        eqBadge: "Thursday from 12:40 PM to 1:25 PM",
        eqPDesc: "Drop by the studio to check out the equipment, watch recordings, or pitch your show ideas!",
        eqJoinTitle: "🎙️ Join the adventure for 2026 / 2027!",
        eqJoinP1: "Are you passionate about sound, news, music, technical work, or hosting? Want to make your voice heard at school?",
        eqJoinP2: "If you want to be part of the official radio team for the upcoming school year (2026/2027 season), look no further!",
        eqJoinP3: "👉 Come meet us directly at the studio on Thursdays at lunchtime!",
        aiMainTitle: "Need help listening?",
        aiMainSub: "Here are simple solutions if you encounter any difficulties on our replay platform.",
        instaMainTitle: "High School Instagram Accounts",
        instaBtn: "View profile"
    },
    bg: { // Bulgare
        splashBtn: "Вход в раздела за повторения",
        navHome: "Начало",
        navTeam: "Екипът",
        navJoin: "Присъединете се към екипа",
        navHelp: "Помощ",
        navCalendar: "Календар",
        navInstagram: "Инстаграм",
        navLogin: "Вход",
        ready: "ГОТОВО ЗА СЛУШАНЕ",
        playing: "В МОМЕНТА СЕ ВЪЗПРОИЗВЕЖДА",
        pause: "ПАУЗА",
        choosePodcast: "🎧 Изберете запис по-долу",
        noPodcast: "Няма подкасти в тази папка.",
        listenBtn: "Слушайте записа",
        confirmDelete: "Сигурни ли сте, че искате за постоянно изтриване на този запис?",
        sectionTitle: "Списък с записи",
        adminTitle: "🛠️ Панел за управление (Собственик)",
        adminSubtitle: "Добавяне на нов запис (чрез връзка от Internet Archive):",
        lblTitle: "Заглавие на предаването:",
        lblInfo: "Дата или подробности:",
        lblFile: "Директна връзка към MP3:",
        btnSubmit: "Добави подкаст",
        uploadStatus: "Запазване на връзката на сървъра...",
        btnLogout: "Изход",
        settingsTitle: "Общи настройки",
        settingsLang: "Език:",
        settingsMedia: "Визуална тема:",
        settingsMediaSsn: "Сезонен режим (по подразбиране)",
        settingsMediaDft: "Тъмен режим",
        settingsMediaEar: "Светъл режим",
        settingsFont: "Размер на шрифта:",
        settingsFontSm: "Малък",
        settingsFontMd: "Нормален",
        settingsFontLg: "Голям",
        settingsSave: "Запази настройките",
        footer: "© 2026 Radio 6 - Зона за повторения на Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Екипът на Radio 6",
        eqSub: "Открийте какво се случва зад кулисите на Radio d'Art 6 в Lycée Arcisse de Caumont в Байо.",
        eqH3Hours: "🕒 Работно време на студиото",
        eqPHours: "Клубът и студиото ви очакват всяка седмица в следните часове:",
        eqBadge: "Четвъртък от 12:40 до 13:25",
        eqPDesc: "Заповядайте в студиото, за да разгледате оборудването, да присъствате на записи или да предложите свои идеи!",
        eqJoinTitle: "🎙️ Присъединете се към приключението за 2026 / 2027!",
        eqJoinP1: "Обичате ли звука, новините, музиката, техниката или воденето? Искате ли гласът ви да се чуе в училище?",
        eqJoinP2: "Ако искате да бъдете част от официалния екип на радиото за следващата учебна година, не се колебайте!",
        eqJoinP3: "👉 Елате да се запознаем директно в студиото в четвъртък по обяд!",
        aiMainTitle: "Имате нужда от помощ при слушане?",
        aiMainSub: "Ето лесни решения, ако срещнете затруднения в нашата платформа.",
        instaMainTitle: "Инстаграм профили на гимназията",
        instaBtn: "Преглед на профила"
    },
    hr: { // Croate
        splashBtn: "Ulaz u prostor za reprize",
        navHome: "Početna",
        navTeam: "Tim",
        navJoin: "Pridruži se timu",
        navHelp: "Pomoć",
        navCalendar: "Kalendar",
        navInstagram: "Instagram",
        navLogin: "Prijava",
        ready: "SPREMNO ZA SLUŠANJE",
        playing: "REPRODUKCIJA U TIJEKU",
        pause: "PAUZA",
        choosePodcast: "🎧 Odaberite reprizu u nastavku",
        noPodcast: "Nema podcasta u ovoj mapi.",
        listenBtn: "Slušaj reprizu",
        confirmDelete: "Jeste li sigurni da želite trajno izbrisati ovu reprizu?",
        sectionTitle: "Popis repriza",
        adminTitle: "🛠️ Upravljačka ploča (Vlasnik)",
        adminSubtitle: "Dodaj novu reprizu (putem veze s Internet Archivea):",
        lblTitle: "Naslov emisije:",
        lblInfo: "Datum ili detalji:",
        lblFile: "Izravna MP3 veza:",
        btnSubmit: "Dodaj podcast",
        uploadStatus: "Spremanje veze na poslužitelj...",
        btnLogout: "Odjava",
        settingsTitle: "Opće postavke",
        settingsLang: "Jezik:",
        settingsMedia: "Vizualna tema:",
        settingsMediaSsn: "Sezonski način (zadano)",
        settingsMediaDft: "Tamni način",
        settingsMediaEar: "Svijetli način",
        settingsFont: "Veličina fonta:",
        settingsFontSm: "Mala",
        settingsFontMd: "Normalna",
        settingsFontLg: "Velika",
        settingsSave: "Spremi postavke",
        footer: "© 2026 Radio 6 - Prostor za reprize Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Tim Radio 6",
        eqSub: "Otkrijte što se događa iza kulisa Radio d'Art 6 u Lycée Arcisse de Caumont u Bayeuxu.",
        eqH3Hours: "🕒 Radno vrijeme studija",
        eqPHours: "Klub i radijski studio čekaju vas svaki tjedan u sljedeće vrijeme:",
        eqBadge: "Četvrtak od 12:40 do 13:25",
        eqPDesc: "Posjetite nas u studiju kako biste upoznali opremu, prisustvovali snimanjima ili predložili svoje ideje!",
        eqJoinTitle: "🎙️ Pridružite se avanturi za 2026. / 2027.!",
        eqJoinP1: "Zanima vas zvuk, vijesti, glazba, tehnika ili vođenje emisija? Želite li da se vaš glas čuje u školi?",
        eqJoinP2: "Ako želite biti dio službenog tima za sljedeću školsku godinu, ne oklijevajte!",
        eqJoinP3: "👉 Dođite nas upoznati izravno u studiju četvrtkom u vrijeme ručka!",
        aiMainTitle: "Trebate pomoć pri slušanju?",
        aiMainSub: "Evo jednostavnih rješenja ako naiđete na poteškoće na našoj platformi.",
        instaMainTitle: "Instagram računi škole",
        instaBtn: "Prikaži profil"
    },
    da: { // Danois
        splashBtn: "Gå til genudsendelsesområdet",
        navHome: "Startside",
        navTeam: "Holdet",
        navJoin: "Bliv en del af holdet",
        navHelp: "Hjælp",
        navCalendar: "Kalender",
        navInstagram: "Instagram",
        navLogin: "Log ind",
        ready: "KLAR TIL AT LYTTE",
        playing: "AFSPILLER",
        pause: "PAUSE",
        choosePodcast: "🎧 Vælg en genudsendelse nedenfor",
        noPodcast: "Ingen podcasts i denne mappe.",
        listenBtn: "Lyt til genudsendelsen",
        confirmDelete: "Er du sikker på, at du vil slette denne genudsendelse permanent?",
        sectionTitle: "Liste over genudsendelser",
        adminTitle: "🛠️ Administrationspanel (Ejer)",
        adminSubtitle: "Tilføj en ny genudsendelse (via Internet Archive-link):",
        lblTitle: "Udsendelsens titel:",
        lblInfo: "Dato eller detaljer:",
        lblFile: "Direkte MP3-link:",
        btnSubmit: "Tilføj podcast",
        uploadStatus: "Gemmer link på serveren...",
        btnLogout: "Log ud",
        settingsTitle: "Generelle indstillinger",
        settingsLang: "Sprog:",
        settingsMedia: "Visuelt tema:",
        settingsMediaSsn: "Sæsontilstand (standard)",
        settingsMediaDft: "Mørk tilstand",
        settingsMediaEar: "Lys tilstand",
        settingsFont: "Skriftstørrelse:",
        settingsFontSm: "Lille",
        settingsFontMd: "Normal",
        settingsFontLg: "Stor",
        settingsSave: "Gem indstillinger",
        footer: "© 2026 Radio 6 - Genudsendelsesområde for Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Radio 6-holdet",
        eqSub: "Oplev hvad der sker bag kulisserne på Radio d'Art 6 på Lycée Arcisse de Caumont i Bayeux.",
        eqH3Hours: "🕒 Studietid",
        eqPHours: "Radioklubben og studiet byder dig velkommen hver uge på følgende tidspunkter:",
        eqBadge: "Torsdag fra 12:40 til 13:25",
        eqPDesc: "Kig forbi studiet for at se udstyret, overvære optagelser eller foreslå dine programidéer!",
        eqJoinTitle: "🎙️ Bliv en del af eventyret for 2026 / 2027!",
        eqJoinP1: "Brænder du for lyd, nyheder, musik, teknik eller værtsskab? Vil du gøre din stemme hørt på skolen?",
        eqJoinP2: "Hvis du vil være en del af det officielle radiohold til næste skoleår, så tøv ikke!",
        eqJoinP3: "👉 Mød os i studiet om torsdagen i frokostpausen!",
        aiMainTitle: "Brug for hjælp til at lytte?",
        aiMainSub: "Her er nemme løsninger, hvis du oplever problemer på vores afspilningsplatform.",
        instaMainTitle: "Gymnasiets Instagram-konti",
        instaBtn: "Se profil"
    },
    es: { // Espagnol
        splashBtn: "Entrar en el espacio de retransmisión",
        navHome: "Inicio",
        navTeam: "El Equipo",
        navJoin: "Unirse al equipo",
        navHelp: "Ayuda",
        navCalendar: "Calendario",
        navInstagram: "Instagram",
        navLogin: "Conexión",
        ready: "LISTO PARA ESCUCHAR",
        playing: "REPRODUCIENDO",
        pause: "PAUSA",
        choosePodcast: "🎧 Elige una retransmisión abajo",
        noPodcast: "No hay podcasts en esta carpeta.",
        listenBtn: "Escuchar la retransmisión",
        confirmDelete: "¿Estás seguro de que quieres eliminar permanentemente esta retransmisión?",
        sectionTitle: "Lista de Retransmisiones",
        adminTitle: "🛠️ Panel de Gestión (Propietario)",
        adminSubtitle: "Añadir una nueva retransmisión (vía enlace de Internet Archive):",
        lblTitle: "Título del programa:",
        lblInfo: "Fecha o detalles:",
        lblFile: "Enlace directo MP3:",
        btnSubmit: "Añadir podcast",
        uploadStatus: "Guardando enlace en el servidor...",
        btnLogout: "Cerrar sesión",
        settingsTitle: "Ajustes Generales",
        settingsLang: "Idioma:",
        settingsMedia: "Tema Visual:",
        settingsMediaSsn: "Modo Estación (por defecto)",
        settingsMediaDft: "Modo Oscuro",
        settingsMediaEar: "Modo Claro",
        settingsFont: "Tamaño de fuente:",
        settingsFontSm: "Pequeña",
        settingsFontMd: "Normal",
        settingsFontLg: "Grande",
        settingsSave: "Guardar ajustes",
        footer: "© 2026 Radio 6 - Espacio de retransmisión del Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "El Equipo de Radio 6",
        eqSub: "Descubre los entresijos de la Radio d'Art 6 del Lycée Arcisse de Caumont en Bayeux.",
        eqH3Hours: "🕒 Horarios de Apertura del Estudio",
        eqPHours: "El club y el estudio de la radio te reciben cada semana en los siguientes horarios:",
        eqBadge: "Jueves de 12:40 a 13:25",
        eqPDesc: "¡Pásate por el estudio para descubrir el equipo, asistir a las grabaciones o proponer tus ideas de programas!",
        eqJoinTitle: "🎙️ ¡Únete a la aventura para 2026 / 2027!",
        eqJoinP1: "¿Te apasiona el sonido, las noticias, la música, la técnica o la locución? ¿Quieres que se escuche tu voz en el instituto?",
        eqJoinP2: "Si quieres formar parte del equipo oficial de la radio para el próximo curso, ¡no lo dudes más!",
        eqJoinP3: "👉 Ven a conocernos directamente al estudio los Jueves a mediodía!",
        aiMainTitle: "¿Necesitas ayuda para escuchar?",
        aiMainSub: "Aquí tienes soluciones sencillas si encuentras alguna dificultad en nuestra plataforma.",
        instaMainTitle: "Cuentas de Instagram del Instituto",
        instaBtn: "Ver perfil"
    },
    et: { // Estonien
        splashBtn: "Sisene järelkuulamise alale",
        navHome: "Avaleht",
        navTeam: "Meeskond",
        navJoin: "Liitu meeskonnaga",
        navHelp: "Abi",
        navCalendar: "Kalender",
        navInstagram: "Instagram",
        navLogin: "Logi sisse",
        ready: "VALMIS KUULAMISEKS",
        playing: "MÄNGIB",
        pause: "PAUS",
        choosePodcast: "🎧 Vali allpool salvestis",
        noPodcast: "Selles kaustas pole taskuhäälingusaateid.",
        listenBtn: "Kuula salvestist",
        confirmDelete: "Kas oled kindel, et soovid selle salvestise jäädavalt kustutada?",
        sectionTitle: "Salvestiste nimekiri",
        adminTitle: "🛠️ Halduspaneel (Omanik)",
        adminSubtitle: "Lisa uus salvestis (Internet Archive'i lingi kaudu):",
        lblTitle: "Saate pealkiri:",
        lblInfo: "Kuupäev või üksikasjad:",
        lblFile: "Otsene MP3 link:",
        btnSubmit: "Lisa taskuhääling",
        uploadStatus: "Lingi salvestamine serverisse...",
        btnLogout: "Logi välja",
        settingsTitle: "Üldseaded",
        settingsLang: "Keel:",
        settingsMedia: "Visuaalne teema:",
        settingsMediaSsn: "Hooajarežiim (vaikimisi)",
        settingsMediaDft: "Tume režiim",
        settingsMediaEar: "Hele režiim",
        settingsFont: "Kirja suurus:",
        settingsFontSm: "Väike",
        settingsFontMd: "Tavaline",
        settingsFontLg: "Suur",
        settingsSave: "Salvesta seaded",
        footer: "© 2026 Radio 6 - Lycée Arcisse de Caumont järelkuulamisala, Bayeux.",
        eqTitle: "Radio 6 meeskond",
        eqSub: "Avasta, mis toimub Radio d'Art 6 kaadritaga Bayeux' Arcisse de Caumonti gümnaasiumis.",
        eqH3Hours: "🕒 Stuudio lahtiolekuajad",
        eqPHours: "Raadioklubi ja stuudio ootavad mind igal nädalal järgmistel kellaaegadel:",
        eqBadge: "Neljapäeval kell 12:40 kuni 13:25",
        eqPDesc: "Astuge stuudiost läbi, et tutvuda tehnikaga, jälgida salvestusi või pakkuda oma saateideid!",
        eqJoinTitle: "🎙️ Liitu seiklusega aastateks 2026 / 2027!",
        eqJoinP1: "Kas oled kirglik heli, uudiste, muusika, tehnika või saatejuhtimise vastu? Soovid oma häält koolis kuuldavaks teha?",
        eqJoinP2: "Kui soovid olla raadio ametlikus meeskonnas järgmisel õppeaastal, ära kõhkle!",
        eqJoinP3: "👉 Tule kohtu meiega otse stuudios neljapäeviti lõunapausi ajal!",
        aiMainTitle: "Vajad kuulamisel abi?",
        aiMainSub: "Siin on lihtsad lahendused, kui teil tekib meie platvormil raskusi.",
        instaMainTitle: "Gümnaasiumi Instagrami kontod",
        instaBtn: "Vaata profiili"
    },
    fi: { // Finnois
        splashBtn: "Siirry kuuntelualueelle",
        navHome: "Etusivu",
        navTeam: "Tiimi",
        navJoin: "Liity tiimiin",
        navHelp: "Ohje",
        navCalendar: "Kalenteri",
        navInstagram: "Instagram",
        navLogin: "Kirjaudu",
        ready: "VALMIS KUUNNELTAVAKSI",
        playing: "TOISTETAAN",
        pause: "TAUKO",
        choosePodcast: "🎧 Valitse uusinta alta",
        noPodcast: "Ei podcasteja tässä kansiossa.",
        listenBtn: "Kuuntele uusinta",
        confirmDelete: "Haluatko varmasti poistaa tämän uusinnan poistettavaksi lopullisesti?",
        sectionTitle: "Uusintojen luettelo",
        adminTitle: "🛠️ Hallintapaneeli (Omistaja)",
        adminSubtitle: "Lisää uusi uusinta (Internet Archive -linkin kautta):",
        lblTitle: "Ohjelman nimi:",
        lblInfo: "Päivämäärä tai tiedot:",
        lblFile: "Suora MP3-linkki:",
        btnSubmit: "Lisää podcast",
        uploadStatus: "Tallennetaan linkkiä palvelimelle...",
        btnLogout: "Kirjaudu ulos",
        settingsTitle: "Yleiset asetukset",
        settingsLang: "Kieli:",
        settingsMedia: "Visuaalinen teema:",
        settingsMediaSsn: "Kausitila (oletus)",
        settingsMediaDft: "Tumma tila",
        settingsMediaEar: "Vaalea tila",
        settingsFont: "Fonttikoko:",
        settingsFontSm: "Pieni",
        settingsFontMd: "Normaali",
        settingsFontLg: "Suuri",
        settingsSave: "Tallenna asetukset",
        footer: "© 2026 Radio 6 - Lycée Arcisse de Caumontin kuuntelualue, Bayeux.",
        eqTitle: "Radio 6 -tiimi",
        eqSub: "Tutustu Radio d'Art 6:n kulissien takaiseen elämään Lycée Arcisse de Caumontissa Bayeux'ssä.",
        eqH3Hours: "🕒 Studioklubin aukioloajat",
        eqPHours: "Radiokerho ja studio toivottavat sinut tervetulleeksi joka viikko seuraavasti:",
        eqBadge: "Torstaisin klo 12:40–13:25",
        eqPDesc: "Tule käymään studiossa katsomassa laitteistoa, seuraamassa äänityksiä tai ehdottamassa omia ohjelmaideoitasi!",
        eqJoinTitle: "🎙️ Liity mukaan seikkailuun kaudelle 2026 / 2027!",
        eqJoinP1: "Oletko innostunut äänestä, uutisista, musiikista, tekniikasta tai juontamisesta? Haluatko äänesi kuuluviin koulussa?",
        eqJoinP2: "Jos haluat olla mukana virallisessa radiotiimissä ensi lukuvuonna, älä epäröi!",
        eqJoinP3: "👉 Tule tapaamaan meitä suoraan studioon torstaisin lounasaikaan!",
        aiMainTitle: "Tarvitsetko apua kuuntelussa?",
        aiMainSub: "Tässä on yksinkertaisia ratkaisuja, jos kohtaat ongelmia alustallamme.",
        instaMainTitle: "Lukion Instagram-tilit",
        instaBtn: "Näytä profiili"
    },
    el: { // Grec
        splashBtn: "Είσοδος στην περιοχή αναπαραγωγής",
        navHome: "Αρχική",
        navTeam: "Η Ομάδα",
        navJoin: "Γίνετε μέλος της ομάδας",
        navHelp: "Βοήθεια",
        navCalendar: "Ημερολόγιο",
        navInstagram: "Instagram",
        navLogin: "Σύνδεση",
        ready: "ΕΤΟΙΜΟ ΓΙΑ ΑΚΡΟΑΣΗ",
        playing: "ΑΝΑΠΑΡΑΓΩΓΗ",
        pause: "ΠΑΥΣΗ",
        choosePodcast: "🎧 Επιλέξτε μια αναπαραγωγή παρακάτω",
        noPodcast: "Δεν υπάρχουν podcast σε αυτόν τον φάκελο.",
        listenBtn: "Ακούστε την αναπαραγωγή",
        confirmDelete: "Είστε βέβαιοι ότι θέλετε να διαγράψετε οριστικά αυτήν την αναπαραγωγή;",
        sectionTitle: "Λίστα Αναπαραγωγών",
        adminTitle: "🛠️ Πίνακας Διαχείρισης (Ιδιοκτήτης)",
        adminSubtitle: "Προσθήκη νέας αναπαραγωγής (μέσω συνδέσμου Internet Archive):",
        lblTitle: "Τίτλος εκπομπής:",
        lblInfo: "Ημερομηνία ή λεπτομέρειες:",
        lblFile: "Άμεσος σύνδεσμος MP3:",
        btnSubmit: "Προσθήκη podcast",
        uploadStatus: "Αποθήκευση συνδέσμου στον διακομιστή...",
        btnLogout: "Αποσύνδεση",
        settingsTitle: "Γενικές Ρυθμίσεις",
        settingsLang: "Γλώσσα:",
        settingsMedia: "Οπτικό Θέμα:",
        settingsMediaSsn: "Εποχιακή λειτουργία (προεπιλογή)",
        settingsMediaDft: "Σκούρα λειτουργία",
        settingsMediaEar: "Φωτεινή λειτουργία",
        settingsFont: "Μέγεθος γραμματοσειράς:",
        settingsFontSm: "Μικρό",
        settingsFontMd: "Κανονικό",
        settingsFontLg: "Μεγάλο",
        settingsSave: "Αποθήκευση ρυθμίσεων",
        footer: "© 2026 Radio 6 - Περιοχή αναπαραγωγής Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Η Ομάδα του Radio 6",
        eqSub: "Ανακαλύψτε τι συμβαίνει στα παρασκήνια του Radio d'Art 6 στο Lycée Arcisse de Caumont στο Bayeux.",
        eqH3Hours: "🕒 Ωράριο Λειτουργίας Στούντιο",
        eqPHours: "Η λέσχη και το στούντιο σας υποδέχονται κάθε εβδομάδα τις ακόλουθες ώρες:",
        eqBadge: "Πέμπτη από τις 12:40 έως τις 13:25",
        eqPDesc: "Περάστε από το στούντιο για να δείτε τον εξοπλισμό, να παρακολουθήσετε ηχογραφήσεις ή να προτείνετε ιδέες!",
        eqJoinTitle: "🎙️ Ελάτε μαζί μας στην περιπέτεια για το 2026 / 2027!",
        eqJoinP1: "Σας αρέσει ο ήχος, τα νέα, η μουσική, η τεχνική ή η παρουσίαση; Θέλετε να ακουστεί η φωνή σας στο λύκειο;",
        eqJoinP2: "Αν θέλετε να γίνετε μέλος της επίσημης ομάδας του ραδιοφώνου για τη νέα σχολική χρονιά, μη διστάσετε!",
        eqJoinP3: "👉 Ελάτε να μας γνωρίσετε απευθείας στο στούντιο τις Πέμπτες το μεσημέρι!",
        aiMainTitle: "Χρειάζεστε βοήθεια για την ακρόαση;",
        aiMainSub: "Εδώ θα βρείτε απλές λύσεις εάν αντιμετωπίζετε δυσκολίες στην πλατφόρμα μας.",
        instaMainTitle: "Λογαριασμοί Instagram του Λυκείου",
        instaBtn: "Προβολή προφίλ"
    },
    hu: { // Hongrois
        splashBtn: "Belépés a visszahallgatási felületre",
        navHome: "Kezdőlap",
        navTeam: "A Csapat",
        navJoin: "Csatlakozz a csapathoz",
        navHelp: "Súgó",
        navCalendar: "Naptár",
        navInstagram: "Instagram",
        navLogin: "Bejelentkezés",
        ready: "HALLGATÁSRA KÉSZ",
        playing: "LEJÁTSZÁS FOLYAMATBAN",
        pause: "SZÜNET",
        choosePodcast: "🎧 Válasszon egy adást az alábbiak közül",
        noPodcast: "Nincs podcast ebben a mappában.",
        listenBtn: "Adás meghallgatása",
        confirmDelete: "Biztosan véglegesen törölni szeretné ezt az adást?",
        sectionTitle: "Adások listája",
        adminTitle: "🛠️ Kezelőpanel (Tulajdonos)",
        adminSubtitle: "Új adás hozzáadása (Internet Archive hivatkozáson keresztül):",
        lblTitle: "Műsor címe:",
        lblInfo: "Dátum vagy részletek:",
        lblFile: "Közvetlen MP3 hivatkozás:",
        btnSubmit: "Podcast hozzáadása",
        uploadStatus: "Hivatkozás mentése a szerverre...",
        btnLogout: "Kijelentkezés",
        settingsTitle: "Általános Beállítások",
        settingsLang: "Nyelv:",
        settingsMedia: "Vizuális téma:",
        settingsMediaSsn: "Szezonális mód (alapértelmezett)",
        settingsMediaDft: "Sötét mód",
        settingsMediaEar: "Világos mód",
        settingsFont: "Betűméret:",
        settingsFontSm: "Kicsi",
        settingsFontMd: "Normál",
        settingsFontLg: "Nagy",
        settingsSave: "Beállítások mentése",
        footer: "© 2026 Radio 6 - Lycée Arcisse de Caumont adásvisszahallgató felülete, Bayeux.",
        eqTitle: "A Radio 6 Csapata",
        eqSub: "Ismerje meg a bayeux-i Lycée Arcisse de Caumont Radio d'Art 6 kulisszatitkait.",
        eqH3Hours: "🕒 A Stúdió Nyitvatartása",
        eqPHours: "A rádióklub és a stúdió minden héten a következő időpontokban várja Önt:",
        eqBadge: "Csütörtökön 12:40 és 13:25 között",
        eqPDesc: "Látogasson el hozzánk a stúdióba, nézze meg a berendezéseket, vegyen részt a felvételeken vagy javasolja ötleteit!",
        eqJoinTitle: "🎙️ Csatlakozz a kalandhoz a 2026 / 2027-es tanévben!",
        eqJoinP1: "Szereted a hangtechnikát, a híreket, a zenét vagy a műsorvezetést? Szeretnéd, ha hallatszana a hangod az iskolában?",
        eqJoinP2: "Ha szeretnél a rádió hivatalos csapatának tagja lenni a következő tanévben, ne habozz!",
        eqJoinP3: "👉 Gyere és találkozz velünk csütörtökönként ebédidőben a stúdióban!",
        aiMainTitle: "Segítségre van szüksége a hallgatáshoz?",
        aiMainSub: "Íme egyszerű megoldások, ha problémába ütközik a felületünkön.",
        instaMainTitle: "A Gimnázium Instagram Fiókjai",
        instaBtn: "Profil megtekintése"
    },
    ga: { // Irlandais
        splashBtn: "Isteach sa réimse athsheanma",
        navHome: "Bhaile",
        navTeam: "An Fhoireann",
        navJoin: "Bígí linn",
        navHelp: "Cabhair",
        navCalendar: "Féilire",
        navInstagram: "Instagram",
        navLogin: "Logáil isteach",
        ready: "RÉIDH LE HÉISTEACHT",
        playing: "AG SEINM",
        pause: "SÓS",
        choosePodcast: "🎧 Roghnaigh athsheoladh thíos",
        noPodcast: "Níl aon phodchraoladh sa fhillteán seo.",
        listenBtn: "Éist leis an athsheoladh",
        confirmDelete: "An bhfuil tú cinnte gur mhaith leat an t-athsheoladh seo a scriosadh go buan?",
        sectionTitle: "Liosta Athsheanta",
        adminTitle: "🛠️ Painéal Bainistíochta (Úinéir)",
        adminSubtitle: "Cuir athsheoladh nua leis (trí nasc Internet Archive):",
        lblTitle: "Teideal an tseó:",
        lblInfo: "Dáta nó sonraí:",
        lblFile: "Nasc díreach MP3:",
        btnSubmit: "Cuir podchraoladh leis",
        uploadStatus: "Nasc á shábháil ar an bhfreastalaí...",
        btnLogout: "Logáil amach",
        settingsTitle: "Socruithe Ginearálta",
        settingsLang: "Teanga:",
        settingsMedia: "Téama Vísseach:",
        settingsMediaSsn: "Mód Séasúir (réamhshocrú)",
        settingsMediaDft: "Mód Dorcha",
        settingsMediaEar: "Mód Solais",
        settingsFont: "Méid an chló:",
        settingsFontSm: "Beag",
        settingsFontMd: "Gnáth",
        settingsFontLg: "Mór",
        settingsSave: "Sábháil socruithe",
        footer: "© 2026 Radio 6 - Limistéar athsheanma Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Foireann Radio 6",
        eqSub: "Faigh amach cad a tharlaíonn taobh thiar de na radhairc ar Radio d'Art 6 ag Lycée Arcisse de Caumont i mBayeux.",
        eqH3Hours: "🕒 Uaireanta Oscailte an Stiúideo",
        eqPHours: "Cuireann an club agus an stiúideo fáilte romhat gach seachtain ag na hamanta seo a leanas:",
        eqBadge: "Déardaoin ó 12:40 p.m. go 1:25 p.m.",
        eqPDesc: "Bígí linn sa stiúideo chun an trealamh a fheiceáil, freastal ar thaifeadtaí nó do smaointe seó a mholadh!",
        eqJoinTitle: "🎙️ Bígí linn don eachtra i 2026 / 2027!",
        eqJoinP1: "An bhfuil suim agat i fuaim, nuacht, ceol, obair theicniúil nó láithreoireacht? Ar mhaith leat go gcloisfear do ghuth ar scoil?",
        eqJoinP2: "Más mian leat a bheith i do bhall d'fhoireann oifigiúil an rádió don bhliain scoile seo chugainn, ná bíodh drogall ort!",
        eqJoinP3: "👉 Tar chun bualadh linn go díreach sa stiúideo ar an Déardaoin ag am lóin!",
        aiMainTitle: "An bhfuil cabhair uait le héisteacht?",
        aiMainSub: "Seo réitigh shimplí má thagann tú ar aon deacracht ar ár n-ardán.",
        instaMainTitle: "Cuntais Instagram na Scoile",
        instaBtn: "Féach ar an bpróifíl"
    },
    it: { // Italien
        splashBtn: "Entra nell'area riproduzione",
        navHome: "Home",
        navTeam: "Il Team",
        navJoin: "Unisciti al team",
        navHelp: "Aiuto",
        navCalendar: "Calendario",
        navInstagram: "Instagram",
        navLogin: "Accedi",
        ready: "PRONTO ALL'ASCOLTO",
        playing: "IN RIPRODUZIONE",
        pause: "PAUSA",
        choosePodcast: "🎧 Scegli un programma qui sotto",
        noPodcast: "Nessun podcast in questa cartella.",
        listenBtn: "Ascolta la riproduzione",
        confirmDelete: "Sei sicuro di voler eliminare definitivamente questa riproduzione?",
        sectionTitle: "Elenco Riproduzioni",
        adminTitle: "🛠️ Pannello di Gestione (Proprietario)",
        adminSubtitle: "Aggiungi una nuova riproduzione (tramite link Internet Archive):",
        lblTitle: "Titolo dello spettacolo:",
        lblInfo: "Data o dettagli:",
        lblFile: "Link diretto MP3:",
        btnSubmit: "Aggiungi podcast",
        uploadStatus: "Salvataggio del link sul server...",
        btnLogout: "Disconnetti",
        settingsTitle: "Impostazioni Generali",
        settingsLang: "Lingua:",
        settingsMedia: "Tema Visivo:",
        settingsMediaSsn: "Modalità Stagione (predefinita)",
        settingsMediaDft: "Modalità Scura",
        settingsMediaEar: "Modalità Chiara",
        settingsFont: "Dimensione carattere:",
        settingsFontSm: "Piccolo",
        settingsFontMd: "Normale",
        settingsFontLg: "Grande",
        settingsSave: "Salva impostazioni",
        footer: "© 2026 Radio 6 - Area riproduzione del Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Il Team di Radio 6",
        eqSub: "Scopri il dietro le quinte di Radio d'Art 6 del Lycée Arcisse de Caumont a Bayeux.",
        eqH3Hours: "🕒 Orari di Apertura dello Studio",
        eqPHours: "Il club e lo studio radiofonico ti accoglono ogni settimana nei seguenti orari:",
        eqBadge: "Giovedì dalle 12:40 alle 13:25",
        eqPDesc: "Vieni a trovarci in studio per scoprire l'attrezzatura, assistere alle registrazioni o proporre le tue idee!",
        eqJoinTitle: "🎙️ Unisciti all'avventura per il 2026 / 2027!",
        eqJoinP1: "Ti appassionano il suono, le notizie, la musica, la tecnica o la conduzione? Vuoi far sentire la tua voce a scuola?",
        eqJoinP2: "Se vuoi far parte del team ufficiale della radio per il prossimo anno scolastico, non esitare!",
        eqJoinP3: "👉 Vieni a conoscerci direttamente in studio il giovedì a pranzo!",
        aiMainTitle: "Serve aiuto per l'ascolto?",
        aiMainSub: "Ecco semplici soluzioni se riscontri difficoltà sulla nostra piattaforma.",
        instaMainTitle: "Account Instagram del Liceo",
        instaBtn: "Vedi profilo"
    },
    lv: { // Letton
        splashBtn: "Ieiet atskaņošanas zonā",
        navHome: "Sākums",
        navTeam: "Komanda",
        navJoin: "Pievienoties komandai",
        navHelp: "Palīdzība",
        navCalendar: "Kalendārs",
        navInstagram: "Instagram",
        navLogin: "Pieslēgties",
        ready: "GATAVS KLAUSĪŠANAI",
        playing: "ATSKAŅO",
        pause: "PAUZE",
        choosePodcast: "🎧 Izvēlieties ierakstu zemāk",
        noPodcast: "Šajā mapē nav podrāžu.",
        listenBtn: "Klausīties ierakstu",
        confirmDelete: "Vai tiešām vēlaties neatgriezeniski dzēst šo ierakstu?",
        sectionTitle: "Ierakstu saraksts",
        adminTitle: "🛠️ Pārvaldības panelis (Īpašnieks)",
        adminSubtitle: "Pievienot jaunu ierakstu (caur Internet Archive saiti):",
        lblTitle: "Raidījuma nosaukums:",
        lblInfo: "Datums vai detaļas:",
        lblFile: "Tiešā MP3 saite:",
        btnSubmit: "Pievienot podrādi",
        uploadStatus: "Saites saglabāšana serverī...",
        btnLogout: "Izrakstīties",
        settingsTitle: "Vispārīgie iestatījumi",
        settingsLang: "Valoda:",
        settingsMedia: "Vizuālā tēma:",
        settingsMediaSsn: "Sezonas režīms (noklusējuma)",
        settingsMediaDft: "Tumšais režīms",
        settingsMediaEar: "Gaišais režīms",
        settingsFont: "Raksta lielums:",
        settingsFontSm: "Mazs",
        settingsFontMd: "Normāls",
        settingsFontLg: "Liels",
        settingsSave: "Saglabāt iestatījumus",
        footer: "© 2026 Radio 6 - Lycée Arcisse de Caumont atskaņošanas zona, Bayeux.",
        eqTitle: "Radio 6 komanda",
        eqSub: "Uzziniet, kas notiek aiz kulisēm Radio d'Art 6 Bayeux Arcisse de Caumont vidusskolā.",
        eqH3Hours: "🕒 Studijas darba laiks",
        eqPHours: "Klubs un radio studija gaida jūs katru nedēļu šādos laikos:",
        eqBadge: "Ceturtdienās no 12:40 līdz 13:25",
        eqPDesc: "Nāciet uz studiju, lai apskatītu aprīkojumu, vērotu ierakstus vai ierosinātu savas idejas!",
        eqJoinTitle: "🎙️ Pievienojies piedzīvojumam 2026. / 2027. gadā!",
        eqJoinP1: "Vai tevi aizrauj skaņa, ziņas, mūzika, tehnika vai vadīšana? Vai vēlies, lai tavu balsi dzird skolā?",
        eqJoinP2: "Ja vēlies būt daļa no oficiālās radio komandas nākamajā mācību gadā, nevilcinies!",
        eqJoinP3: "👉 Nāc un tiecies ar mums studijā ceturtdienās pusdienlaikā!",
        aiMainTitle: "Nepieciešama palīdzība klausoties?",
        aiMainSub: "Šeit ir vienkārši risinājumi, ja rodas grūtības mūsu platformā.",
        instaMainTitle: "Vidusskolas Instagram konti",
        instaBtn: "Skatīt profilu"
    },
    lt: { // Lituanien
        splashBtn: "Įeiti į perklausų erdvę",
        navHome: "Pagrindinis",
        navTeam: "Komanda",
        navJoin: "Prisijungti prie komandos",
        navHelp: "Pagalba",
        navCalendar: "Kalendorius",
        navInstagram: "Instagram",
        navLogin: "Prisijungti",
        ready: "PARUOŠTA KLAUSYMUI",
        playing: "GROJAMA",
        pause: "PAUZĖ",
        choosePodcast: "🎧 Pasirinkite įrašą žemiau",
        noPodcast: "Šiame aplanke podcast'ų nėra.",
        listenBtn: "Klausytis įrašo",
        confirmDelete: "Ar tikrai norite visam laikui ištrinti šį įrašą?",
        sectionTitle: "Įrašų sąrašas",
        adminTitle: "🛠️ Valdymo skydas (Savininkas)",
        adminSubtitle: "Pridėti naują įrašą (per Internet Archive nuorodą):",
        lblTitle: "Laidos pavadinimas:",
        lblInfo: "Data arba detalės:",
        lblFile: "Tiesioginė MP3 nuoroda:",
        btnSubmit: "Pridėti podcast'ą",
        uploadStatus: "Nuoroda saugoma serveryje...",
        btnLogout: "Atsijungti",
        settingsTitle: "Bendrieji nustatymai",
        settingsLang: "Kalba:",
        settingsMedia: "Vizualinė tema:",
        settingsMediaSsn: "Sezoninis režimas (numatytasis)",
        settingsMediaDft: "Tamsusis režimas",
        settingsMediaEar: "Šviesusis režimas",
        settingsFont: "Šrifto dydis:",
        settingsFontSm: "Mažas",
        settingsFontMd: "Normalus",
        settingsFontLg: "Didelis",
        settingsSave: "Išsaugoti nustatymus",
        footer: "© 2026 Radio 6 - Lycée Arcisse de Caumont perklausų erdvė, Bayeux.",
        eqTitle: "Radio 6 komanda",
        eqSub: "Sužinokite, kas vyksta už kulisių Radio d'Art 6 Bayeux Arcisse de Caumont gimnazijoje.",
        eqH3Hours: "🕒 Studijos darbo laikas",
        eqPHours: "Klubas ir radijo studija jūsų laukia kiekvieną savaitę šiuo laiku:",
        eqBadge: "Ketvirtadienį nuo 12:40 iki 13:25",
        eqPDesc: "Apsilankykite studijoje, apžiūrėkite įrangą, stebėkite įrašus arba pasiūlykite savo idėjas!",
        eqJoinTitle: "🎙️ Prisijunkite prie nuotykio 2026 / 2027 m.!",
        eqJoinP1: "Mėgsti garsą, naujienas, muziką, techniką ar vedėjo darbą? Nori, kad tavo balsas skambėtų mokykloje?",
        eqJoinP2: "Jei nori tapti oficialios radijo komandos dalimi ateinantiems mokslo metams, nedvejok!",
        eqJoinP3: "👉 Užsuk susipažinti tiesiai į studiją ketvirtadieniais per pietų pertrauką!",
        aiMainTitle: "Reikia pagalbos klausantis?",
        aiMainSub: "Štai paprasti sprendimai, jei kyla sunkumų mūsų platformoje.",
        instaMainTitle: "Gimnazijos Instagram paskyros",
        instaBtn: "Rodyti profilį"
    },
    mt: { // Maltais
        splashBtn: "Daħħal fl-ambjent tar-replay",
        navHome: "L-Ewwel Paġna",
        navTeam: "It-Tim",
        navJoin: "Ingħaqad mat-tim",
        navHelp: "Għajnuna",
        navCalendar: "Kalendarju",
        navInstagram: "Instagram",
        navLogin: "Inqabbad",
        ready: "LEST BIEX TISMA’",
        playing: "QAD TINDAGGI",
        pause: "PAWŻA",
        choosePodcast: "🎧 Agħżel replay hawn taħt",
        noPodcast: "L-ebda podcast f'din il-folder.",
        listenBtn: "Isma' r-replay",
        confirmDelete: "Żgur li trid tħassar din ir-replay b'mod permanenti?",
        sectionTitle: "Lista ta' Replays",
        adminTitle: "🛠️ Panew ta' Ġestjoni (Sided)",
        adminSubtitle: "Żid replay ġdida (permezz ta' link ta' Internet Archive):",
        lblTitle: "Titlu tal-programm:",
        lblInfo: "Data jew dettalji:",
        lblFile: "Link dirett MP3:",
        btnSubmit: "Żid podcast",
        uploadStatus: "Iffrankar tal-link fuq is-server...",
        btnLogout: "Oħroġ",
        settingsTitle: "Settings Ġenerali",
        settingsLang: "Lingwa:",
        settingsMedia: "Tema Viżiva:",
        settingsMediaSsn: "Mod Staġjonali (default)",
        settingsMediaDft: "Mod Dark",
        settingsMediaEar: "Mod Dawl",
        settingsFont: "Daqs tal-font:",
        settingsFontSm: "Żgħir",
        settingsFontMd: "Normali",
        settingsFontLg: "Kbir",
        settingsSave: "Iffranka s-settings",
        footer: "© 2026 Radio 6 - Żona ta' replay ta' Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "It-Tim ta' Radio 6",
        eqSub: "Skopri x'jiġri wara l-kwinti ta' Radio d'Art 6 f'Lycée Arcisse de Caumont f'Bayeux.",
        eqH3Hours: "🕒 Ħinijiet tal-Apertura tal-Istudju",
        eqPHours: "Il-klabb u l-istudju tar-radju jilqgħuk kull ġimgħa f'dawn il-ħinijiet:",
        eqBadge: "Il-Ħamis minn 12:40 sa 13:25",
        eqPDesc: "Għaddi mill-istudju biex tara t-tagħmir, tattendi għar-reġistrazzjonijiet jew tipproponi l-ideat tiegħek!",
        eqJoinTitle: "🎙️ Ingħaqad magħna għall-avventura ta' 2026 / 2027!",
        eqJoinP1: "Tħobb il-ħoss, l-aħbarijiet, il-mużika, it-teknika jew il-preżentazzjoni? Trid li leħnek jinstema' fl-iskola?",
        eqJoinP2: "Jekk trid tkun parti mit-tim uffiċjali tar-radju għas-sena skolastika li ġejja, toqgħodx lura!",
        eqJoinP3: "👉 Ejjew iltaqa' magħna direttament fl-istudju nhar ta' Ħamis f'ħin l-ikel!",
        aiMainTitle: "Għandek bżonn għajnuna biex tisma'?",
        aiMainSub: "Hawn huma soluzzjonijiet sempliċi jekk tiltaqa' ma' diffikultajiet fuq il-pjattaforma tagħna.",
        instaMainTitle: "Kontijiet Instagram tal-Iskola",
        instaBtn: "Ara l-profil"
    },
    nl: { // Néerlandais
        splashBtn: "Ga naar de herbeluisterruimte",
        navHome: "Startpagina",
        navTeam: "Het Team",
        navJoin: "Word lid van het team",
        navHelp: "Help",
        navCalendar: "Kalender",
        navInstagram: "Instagram",
        navLogin: "Inloggen",
        ready: "KLAAR OM TE LUISTEREN",
        playing: "AFSPELEN",
        pause: "PAUZE",
        choosePodcast: "🎧 Kies hieronder een uitzending",
        noPodcast: "Geen podcasts in deze map.",
        listenBtn: "Luister naar de herhaling",
        confirmDelete: "Weet u zeker dat u deze herhaling definitief wilt verwijderen?",
        sectionTitle: "Lijst van Herhalingen",
        adminTitle: "🛠️ Beheerderspaneel (Eigenaar)",
        adminSubtitle: "Nieuwe herhaling toevoegen (via Internet Archive link):",
        lblTitle: "Titel van de uitzending:",
        lblInfo: "Datum of details:",
        lblFile: "Directe MP3-link:",
        btnSubmit: "Podcast toevoegen",
        uploadStatus: "Link opslaan op server...",
        btnLogout: "Uitloggen",
        settingsTitle: "Algemene Instellingen",
        settingsLang: "Taal:",
        settingsMedia: "Visueel Thema:",
        settingsMediaSsn: "Seizoensmodus (standaard)",
        settingsMediaDft: "Donkere modus",
        settingsMediaEar: "Lichte modus",
        settingsFont: "Lettergrootte:",
        settingsFontSm: "Klein",
        settingsFontMd: "Normaal",
        settingsFontLg: "Groot",
        settingsSave: "Instellingen opslaan",
        footer: "© 2026 Radio 6 - Herbeluisterruimte van het Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Het Team van Radio 6",
        eqSub: "Ontdek wat er zich achter de schermen afspeelt bij Radio d'Art 6 op het Lycée Arcisse de Caumont in Bayeux.",
        eqH3Hours: "🕒 Openingstijden van de Studio",
        eqPHours: "De club en de radiostudio verwelkomen u elke week op de volgende tijden:",
        eqBadge: "Donderdag van 12:40 tot 13:25",
        eqPDesc: "Kom langs in de studio om de apparatuur te bekijken, opnames bij te wonen of ideeën voor te stellen!",
        eqJoinTitle: "🎙️ Doe mee aan het avontuur voor 2026 / 2027!",
        eqJoinP1: "Ben je gepassioneerd door geluid, nieuws, muziek, techniek of presenteren? Wil je je stem laten horen op school?",
        eqJoinP2: "Als je deel wilt uitmaken van het officiële radioteam voor komend schooljaar, aarzel dan niet!",
        eqJoinP3: "👉 Kom ons op donderdag tijdens de lunch rechtstreeks ontmoeten in de studio!",
        aiMainTitle: "Hulp nodig bij het luisteren?",
        aiMainSub: "Hier zijn eenvoudige oplossingen als u problemen ondervindt op ons platform.",
        instaMainTitle: "Instagram-accounts van de school",
        instaBtn: "Bekijk profiel"
    },
    pl: { // Polonais
        splashBtn: "Wejdź do strefy powtórek",
        navHome: "Strona główna",
        navTeam: "Zespół",
        navJoin: "Dołącz do zespołu",
        navHelp: "Pomoc",
        navCalendar: "Kalendarz",
        navInstagram: "Instagram",
        navLogin: "Zaloguj się",
        ready: "GOTOWE DO SŁUCHANIA",
        playing: "ODTWARZANIE",
        pause: "PAUZA",
        choosePodcast: "🎧 Wybierz audycję poniżej",
        noPodcast: "Brak podcastów w tym folderze.",
        listenBtn: "Odsłuchaj powtórkę",
        confirmDelete: "Czy na pewno chcesz trwale usunąć tę powtórkę?",
        sectionTitle: "Lista Powtórek",
        adminTitle: "🛠️ Panel Zarządzania (Właściciel)",
        adminSubtitle: "Dodaj nową powtórkę (przez link z Internet Archive):",
        lblTitle: "Tytuł audycji:",
        lblInfo: "Data lub szczegóły:",
        lblFile: "Bezpośredni link MP3:",
        btnSubmit: "Dodaj podcast",
        uploadStatus: "Zapisywanie linku na serwerze...",
        btnLogout: "Wyloguj się",
        settingsTitle: "Ustawienia Ogólne",
        settingsLang: "Język:",
        settingsMedia: "Motyw Wizualny:",
        settingsMediaSsn: "Tryb Sezonowy (domyślny)",
        settingsMediaDft: "Tryb Ciemny",
        settingsMediaEar: "Tryb Jasny",
        settingsFont: "Rozmiar czcionki:",
        settingsFontSm: "Mała",
        settingsFontMd: "Normalna",
        settingsFontLg: "Duża",
        settingsSave: "Zapisz ustawienia",
        footer: "© 2026 Radio 6 - Strefa powtórek Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Zespół Radio 6",
        eqSub: "Odkryj kulisy pracy Radio d'Art 6 w Lycée Arcisse de Caumont w Bayeux.",
        eqH3Hours: "🕒 Godziny Otwarcia Studia",
        eqPHours: "Klub i studio radiowe zapraszają co tydzień w następujących godzinach:",
        eqBadge: "Czwartek od 12:40 do 13:25",
        eqPDesc: "Odwiedź nas w studio, zobacz sprzęt, weź udział w nagraniach lub zaproponuj własne pomysły!",
        eqJoinTitle: "🎙️ Dołącz do przygody na rok 2026 / 2027!",
        eqJoinP1: "Pasjonujesz się dźwiękiem, wiadomościami, muzyką, techniką lub prowadzeniem audycji? Chcesz, aby Twój głos był słyszalny w szkole?",
        eqJoinP2: "Jeśli chcesz dołączyć do oficjalnego zespołu radiowego na nadchodzący rok szkolny, nie zwlekaj!",
        eqJoinP3: "👉 Przyjdź spotkać się z nami bezpośrednio w studio w czwartkowe południe!",
        aiMainTitle: "Potrzebujesz pomocy ze słuchaniem?",
        aiMainSub: "Oto proste rozwiązania, jeśli napotkasz trudności na naszej platformie.",
        instaMainTitle: "Konta Instagram Liceum",
        instaBtn: "Zobacz profil"
    },
    pt: { // Portugais
        splashBtn: "Entrar no espaço de retransmissão",
        navHome: "Início",
        navTeam: "A Equipa",
        navJoin: "Junte-se à equipa",
        navHelp: "Ajuda",
        navCalendar: "Calendário",
        navInstagram: "Instagram",
        navLogin: "Iniciar sessão",
        ready: "PRONTO PARA OUVIR",
        playing: "A REPRODUZIR",
        pause: "PAUSA",
        choosePodcast: "🎧 Escolha uma gravação abaixo",
        noPodcast: "Nenhum podcast nesta pasta.",
        listenBtn: "Ouvir a gravação",
        confirmDelete: "Tem a certeza de que pretende eliminar permanentemente esta gravação?",
        sectionTitle: "Lista de Gravações",
        adminTitle: "🛠️ Painel de Gestão (Proprietário)",
        adminSubtitle: "Adicionar uma nova gravação (via link do Internet Archive):",
        lblTitle: "Título do programa:",
        lblInfo: "Data ou detalhes:",
        lblFile: "Link direto MP3:",
        btnSubmit: "Adicionar podcast",
        uploadStatus: "A guardar o link no servidor...",
        btnLogout: "Terminar sessão",
        settingsTitle: "Definições Gerais",
        settingsLang: "Idioma:",
        settingsMedia: "Tema Visual:",
        settingsMediaSsn: "Modo Estação (predefinido)",
        settingsMediaDft: "Modo Escuro",
        settingsMediaEar: "Modo Claro",
        settingsFont: "Tamanho da fonte:",
        settingsFontSm: "Pequeno",
        settingsFontMd: "Normal",
        settingsFontLg: "Grande",
        settingsSave: "Guardar definições",
        footer: "© 2026 Radio 6 - Espaço de retransmissão do Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "A Equipa da Radio 6",
        eqSub: "Descubra os bastidores da Radio d'Art 6 do Lycée Arcisse de Caumont em Bayeux.",
        eqH3Hours: "🕒 Horário de Funcionamento do Estúdio",
        eqPHours: "O clube e o estúdio de rádio acolhem-no todas as semanas nos seguintes horários:",
        eqBadge: "Quinta-feira das 12:40 às 13:25",
        eqPDesc: "Passe pelo estúdio para ver o equipamento, assistir a gravações ou propor as suas ideias!",
        eqJoinTitle: "🎙️ Junte-se à aventura para 2026 / 2027!",
        eqJoinP1: "És apaixonado por som, notícias, música, técnica ou apresentação? Queres fazer ouvir a tua voz na escola?",
        eqJoinP2: "Se queres fazer parte da equipa oficial da rádio para o próximo ano letivo, não hesites!",
        eqJoinP3: "👉 Vem conhecer-nos diretamente ao estúdio nas quintas-feiras ao almoço!",
        aiMainTitle: "Precisa de ajuda para ouvir?",
        aiMainSub: "Aqui estão soluções simples se encontrar dificuldades na nossa plataforma.",
        instaMainTitle: "Contas de Instagram da Escola",
        instaBtn: "Ver perfil"
    },
    ro: { // Roumain
        splashBtn: "Intră în spațiul de difuzare",
        navHome: "Acasă",
        navTeam: "Echipa",
        navJoin: "Alătură-te echipei",
        navHelp: "Ajutor",
        navCalendar: "Calendar",
        navInstagram: "Instagram",
        navLogin: "Autentificare",
        ready: "GATA DE ASCULTARE",
        playing: "SE REDĂ",
        pause: "PAUZĂ",
        choosePodcast: "🎧 Alegeți o înregistrare mai jos",
        noPodcast: "Niciun podcast în acest dosar.",
        listenBtn: "Ascultă înregistrarea",
        confirmDelete: "Sunteți sigur că doriți ștergerea definitivă a acestei înregistrări?",
        sectionTitle: "Lista Înregistrărilor",
        adminTitle: "🛠️ Panou de Administrare (Proprietar)",
        adminSubtitle: "Adăugați o nouă înregistrare (prin link Internet Archive):",
        lblTitle: "Titlul emisiunii:",
        lblInfo: "Dată sau detalii:",
        lblFile: "Link direct MP3:",
        btnSubmit: "Adaugă podcast",
        uploadStatus: "Se salvează linkul pe server...",
        btnLogout: "Deconectare",
        settingsTitle: "Setări Generale",
        settingsLang: "Limbă:",
        settingsMedia: "Temă Vizuală:",
        settingsMediaSsn: "Mod Sezon (implicit)",
        settingsMediaDft: "Mod Întunecat",
        settingsMediaEar: "Mod Luminos",
        settingsFont: "Dimensiune font:",
        settingsFontSm: "Mic",
        settingsFontMd: "Normal",
        settingsFontLg: "Mare",
        settingsSave: "Salvează setările",
        footer: "© 2026 Radio 6 - Spațiul de difuzare al Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Echipa Radio 6",
        eqSub: "Descoperiți culisele Radio d'Art 6 din cadrul Lycée Arcisse de Caumont din Bayeux.",
        eqH3Hours: "🕒 Programul Studioului",
        eqPHours: "Clubul și studioul radio vă așteaptă în fiecare săptămână la următoarele ore:",
        eqBadge: "Joi de la 12:40 la 13:25",
        eqPDesc: "Treceți pe la studio pentru a vedea echipamentele, a asista la înregistrări sau a propune idei!",
        eqJoinTitle: "🎙️ Alătură-te aventurii pentru 2026 / 2027!",
        eqJoinP1: "Ești pasionat de sunet, știri, muzică, tehnică sau prezentare? Vrei să-ți faci vocea auzită în liceu?",
        eqJoinP2: "Dacă vrei să faci parte din echipa oficială a radioului pentru anul școlar viitor, nu ezita!",
        eqJoinP3: "👉 Vino să ne cunoști direct în studio joia la prânz!",
        aiMainTitle: "Aveți nevoie de ajutor pentru ascultare?",
        aiMainSub: "Iată soluții simple dacă întâmpinați dificultăți pe platforma noastră.",
        instaMainTitle: "Conturile de Instagram ale Liceului",
        instaBtn: "Vezi profilul"
    },
    sk: { // Slovaque
        splashBtn: "Vstúpiť do priestoru archívu",
        navHome: "Domov",
        navTeam: "Tím",
        navJoin: "Pridať sa k tímu",
        navHelp: "Pomoc",
        navCalendar: "Kalendár",
        navInstagram: "Instagram",
        navLogin: "Prihlásiť sa",
        ready: "PRIPRAVENÉ NA POČÚVANIE",
        playing: "PREHRÁVA SA",
        pause: "PAUZA",
        choosePodcast: "🎧 Vyberte si záznam nižšie",
        noPodcast: "V tomto priečinku nie sú žiadne podcasty.",
        listenBtn: "Počúvať záznam",
        confirmDelete: "Naozaj chcete natrvalo vymazať tento záznam?",
        sectionTitle: "Zoznam záznamov",
        adminTitle: "🛠️ Správcovský panel (Vlastník)",
        adminSubtitle: "Pridať nový záznam (cez odkaz na Internet Archive):",
        lblTitle: "Názov relácie:",
        lblInfo: "Dátum alebo podrobnosti:",
        lblFile: "Priamy MP3 odkaz:",
        btnSubmit: "Pridať podcast",
        uploadStatus: "Ukladanie odkazu na server...",
        btnLogout: "Odhlásiť sa",
        settingsTitle: "Všeobecné nastavenia",
        settingsLang: "Jazyk:",
        settingsMedia: "Vizuálna téma:",
        settingsMediaSsn: "Sezónny režim (predvolený)",
        settingsMediaDft: "Tmavý režim",
        settingsMediaEar: "Svetlý režim",
        settingsFont: "Veľkosť písma:",
        settingsFontSm: "Malé",
        settingsFontMd: "Normálne",
        settingsFontLg: "Veľké",
        settingsSave: "Uložiť nastavenia",
        footer: "© 2026 Radio 6 - Archív vysielania Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Tím Radio 6",
        eqSub: "Spoznajte zákulisie Radio d'Art 6 na Lycée Arcisse de Caumont v Bayeux.",
        eqH3Hours: "🕒 Otváracie hodiny štúdia",
        eqPHours: "Klub a rádio štúdio vás privítajú každý týždeň v týchto časoch:",
        eqBadge: "Štvrtok od 12:40 do 13:25",
        eqPDesc: "Príďte do štúdia pozrieť si techniku, zúčastniť sa nahrávania alebo navrhnúť vlastné nápady!",
        eqJoinTitle: "🎙️ Pridajte sa k dobrodružstvu na rok 2026 / 2027!",
        eqJoinP1: "Máš vášeň pre zvuk, správy, hudbu, techniku alebo moderovanie? Chceš, aby bol tvoj hlas počuť na škole?",
        eqJoinP2: "Ak chceš byť súčasťou oficiálneho tímu rádia pre budúci školský rok, neváhaj!",
        eqJoinP3: "👉 Príď sa s nami stretnúť priamo do štúdia vo štvrtok cez obed!",
        aiMainTitle: "Potrebujete pomoc s počúvaním?",
        aiMainSub: "Tu sú jednoduché riešenia, ak narazíte na problémy na našej platforme.",
        instaMainTitle: "Instagramové účty školy",
        instaBtn: "Zobraziť profil"
    },
    sl: { // Slovène
        splashBtn: "Vstopite v območje za ponovitve",
        navHome: "Domov",
        navTeam: "Ekipa",
        navJoin: "Pridružite se ekipi",
        navHelp: "Pomoč",
        navCalendar: "Koledar",
        navInstagram: "Instagram",
        navLogin: "Prijava",
        ready: "PRIPRAVLJENO ZA POSLUŠANJE",
        playing: "PREDVAJANJE",
        pause: "PREMOR",
        choosePodcast: "🎧 Izberite ponovitev spodaj",
        noPodcast: "V tej mapi ni podkastov.",
        listenBtn: "Poslušaj ponovitev",
        confirmDelete: "Ali ste prepričani, da želite trajno izbrisati to ponovitev?",
        sectionTitle: "Seznam ponovitev",
        adminTitle: "🛠️ Nadzorna plošča (Lastnik)",
        adminSubtitle: "Dodaj novo ponovitev (preko povezave Internet Archive):",
        lblTitle: "Naslov oddaje:",
        lblInfo: "Datum ali podrobnosti:",
        lblFile: "Neposredna MP3 povezava:",
        btnSubmit: "Dodaj podkast",
        uploadStatus: "Shranjevanje povezave na strežnik...",
        btnLogout: "Odjava",
        settingsTitle: "Splošne nastavitve",
        settingsLang: "Jezik:",
        settingsMedia: "Vizualna tema:",
        settingsMediaSsn: "Sezonski način (privzeto)",
        settingsMediaDft: "Temni način",
        settingsMediaEar: "Svetli način",
        settingsFont: "Velikost pisave:",
        settingsFontSm: "Majhna",
        settingsFontMd: "Navadna",
        settingsFontLg: "Velika",
        settingsSave: "Shrani nastavitve",
        footer: "© 2026 Radio 6 - Območje za ponovitve Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Ekipa Radio 6",
        eqSub: "Odkrijte ozadje Radio d'Art 6 na Lycée Arcisse de Caumont v Bayeuxu.",
        eqH3Hours: "🕒 Urnik studia",
        eqPHours: "Klub in radijski studio vas pričakujeta vsak teden ob naslednjih urah:",
        eqBadge: "Četrtek od 12:40 do 13:25",
        eqPDesc: "Obiščite nas v studiu, oglejte si opremo, prisostvujte snemanju ali predlagajte svoje ideje!",
        eqJoinTitle: "🎙️ Pridružite se pustolovščini za 2026 / 2027!",
        eqJoinP1: "Te zanima zvok, novice, glasba, tehnika ali vodenje oddaj? Želiš, da se tvoj glas sliši v šoli?",
        eqJoinP2: "Če želiš biti del uradne radijske ekipe za naslednje šolsko leto, ne oklevaj!",
        eqJoinP3: "👉 Pridi in nas spoznaj neposredno v studiu ob četrtkih med kosilom!",
        aiMainTitle: "Rabiš pomoč pri poslušanju?",
        aiMainSub: "Tukaj so preproste rešitve, če naletite na težave na naši platformi.",
        instaMainTitle: "Instagram računi šole",
        instaBtn: "Ogled profila"
    },
    sv: { // Suédois
        splashBtn: "Gå till reprisområdet",
        navHome: "Hem",
        navTeam: "Teamet",
        navJoin: "Gå med i teamet",
        navHelp: "Hjälp",
        navCalendar: "Kalender",
        navInstagram: "Instagram",
        navLogin: "Logga in",
        ready: "REDO ATT LYSSNA",
        playing: "SPELAR",
        pause: "PAUS",
        choosePodcast: "🎧 Välj en repris nedan",
        noPodcast: "Inga poddar i den här mappen.",
        listenBtn: "Lyssna på reprisen",
        confirmDelete: "Är du säker på att du vill ta bort den här reprisen permanent?",
        sectionTitle: "Lista över repriser",
        adminTitle: "🛠️ Hanteringspanel (Ägare)",
        adminSubtitle: "Lägg till en ny reprissändning (via Internet Archive-länk):",
        lblTitle: "Programtitel:",
        lblInfo: "Datum eller detaljer:",
        lblFile: "Direkt MP3-länk:",
        btnSubmit: "Lägg till podcast",
        uploadStatus: "Sparar länk på servern...",
        btnLogout: "Logga ut",
        settingsTitle: "Allmänna inställningar",
        settingsLang: "Språk:",
        settingsMedia: "Visuellt tema:",
        settingsMediaSsn: "Säsongsläge (standard)",
        settingsMediaDft: "Mörkt läge",
        settingsMediaEar: "Ljust läge",
        settingsFont: "Teckenstorlek:",
        settingsFontSm: "Liten",
        settingsFontMd: "Normal",
        settingsFontLg: "Stor",
        settingsSave: "Spara inställningar",
        footer: "© 2026 Radio 6 - Reprisområde för Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Radio 6-teamet",
        eqSub: "Upptäck vad som händer bakom kulisserna på Radio d'Art 6 på Lycée Arcisse de Caumont i Bayeux.",
        eqH3Hours: "🕒 Studions öppettider",
        eqPHours: "Radioklubben och studion välkomnar dig varje vecka under följande tider:",
        eqBadge: "Torsdagar från 12:40 till 13:25",
        eqPDesc: "Kom förbi studion för att kolla in utrustningen, titta på inspelningar eller föreslå dina idéer!",
        eqJoinTitle: "🎙️ Bli en del av äventyret för 2026 / 2027!",
        eqJoinP1: "Brinner du för ljud, nyheter, musik, teknik eller att sända? Vill du göra din röst hörd i skolan?",
        eqJoinP2: "Om du vill vara med i det officiella radioteamet inför nästa läsår, tveka inte!",
        eqJoinP3: "👉 Träffa oss i studion på torsdagar under lunchen!",
        aiMainTitle: "Behöver du hjälp med att lyssna?",
        aiMainSub: "Här är enkla lösningar om du stöter på problem på vår plattform.",
        instaMainTitle: "Gymnasieskolans Instagram-konton",
        instaBtn: "Visa profil"
    },
    cs: { // Tchèque
        splashBtn: "Vstoupit do archivu vysílání",
        navHome: "Domů",
        navTeam: "Tým",
        navJoin: "Připojit se k týmu",
        navHelp: "Nápověda",
        navCalendar: "Kalendář",
        navInstagram: "Instagram",
        navLogin: "Přihlásit se",
        ready: "PŘIPRAVENO K POSLECHU",
        playing: "PŘEHRÁVÁ SE",
        pause: "PAUZA",
        choosePodcast: "🎧 Vyberte si záznam níže",
        noPodcast: "V této složce nejsou žádné podcasty.",
        listenBtn: "Poslechnout záznam",
        confirmDelete: "Opravdu chcete tento záznam trvale smazat?",
        sectionTitle: "Seznam záznamů",
        adminTitle: "🛠️ Správcovský panel (Vlastník)",
        adminSubtitle: "Přidat nový záznam (přes odkaz z Internet Archive):",
        lblTitle: "Název pořadu:",
        lblInfo: "Datum nebo podrobnosti:",
        lblFile: "Přímý MP3 odkaz:",
        btnSubmit: "Přidat podcast",
        uploadStatus: "Ukládání odkazu na server...",
        btnLogout: "Odhlásit se",
        settingsTitle: "Obecná nastavení",
        settingsLang: "Jazyk:",
        settingsMedia: "Vizuální motiv:",
        settingsMediaSsn: "Sezónní režim (výchozí)",
        settingsMediaDft: "Tmavý režim",
        settingsMediaEar: "Světlý režim",
        settingsFont: "Velikost písma:",
        settingsFontSm: "Malé",
        settingsFontMd: "Normální",
        settingsFontLg: "Velké",
        settingsSave: "Uložit nastavení",
        footer: "© 2026 Radio 6 - Archiv vysílání Lycée Arcisse de Caumont, Bayeux.",
        eqTitle: "Tým Radio 6",
        eqSub: "Objevte zákulisí Radio d'Art 6 na Lycée Arcisse de Caumont v Bayeux.",
        eqH3Hours: "🕒 Otevírací doba studia",
        eqPHours: "Radioklub a studio vás přivítají každý týden v následujících časech:",
        eqBadge: "Čtvrtek od 12:40 do 13:25",
        eqPDesc: "Stavte se v rozhlasovém studiu, prohlédněte si vybavení, podívejte se na natáčení nebo navrhněte své nápady!",
        eqJoinTitle: "🎙️ Připojte se k dobrodružství pro rok 2026 / 2027!",
        eqJoinP1: "Máš vášeň pro zvuk, zprávy, hudbu, techniku nebo moderování? Chceš, aby byl tvůj hlas ve škole slyšet?",
        eqJoinP2: "Pokud se chceš stát součástí oficiálního týmu rádia pro příští školní rok, neváhej!",
        eqJoinP3: "👉 Přijď se za námi podívat přímo do studia ve čtvrtek o polední pauze!",
        aiMainTitle: "Potřebujete pomoct s poslechem?",
        aiMainSub: "Zde jsou jednoduchá řešení, pokud narazíte na potíže s přehráváním.",
        instaMainTitle: "Instagramové účty školy",
        instaBtn: "Zobrazit profil"
    }
};
